blog/urls.py
from django.conf.urls import patterns, url

from blog import views

urlpatterns = patterns('',
	url(r'^$', views.IndexView.as_view(), name='index'),
	url(r'^titledposts$', 'blog.views.getRecentPosts'),
	url(r'^titledposts/$', 'blog.views.getRecentPosts'),
	url(r'^titledposts/(?P<selected_page>\d+)/?$', 'blog.views.getRecentPosts'),
	url(r'^titledposts/(?P<postSlug>[-a-zA-Z0-9]+)/?$', 'blog.views.getPost'),
	# Blog posts
)

mysite/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^mysite/', include('mysite.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
	url(r'^blog/', include('blog.urls', namespace="blog")),
	url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^admin/', include(admin.site.urls)),
)

polls/urls.py
from django.conf.urls import patterns, url

from polls import views

urlpatterns = patterns('',
url(r'^$', views.IndexView.as_view(), name='index'),
   url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
   url(r'^(?P<pk>\d+)/results/$', views.ResultsView.as_view(), name='results'),
   url(r'^(?P<poll_id>\d+)/vote/$', views.vote, name='vote'),
)

blog/models.py
from django.db import models
from django.utils import timezone
import datetime

class Post(models.Model):
	text = models.CharField(max_length=1000)
	pub_date = models.DateTimeField('date published')
	def was_published_recently(self):
		return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
	was_published_recently.admin_order_field = 'pub_date'
	was_published_recently.boolean = True
	was_published_recently.short_description = 'Published recently?'
	def __unicode__(self):  # Python 3: def __str__(self):
		return self.text

class TitledPost(models.Model):
	title = models.CharField(max_length=200)
	text = models.TextField()
	pub_date = models.DateTimeField('date published')
	slug = models.SlugField(max_length=40, unique=True)
	def was_published_recently(self):
		return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
	was_published_recently.admin_order_field = 'pub_date'
	was_published_recently.boolean = True
	was_published_recently.short_description = 'Published recently?'
	def __unicode__(self):  # Python 3: def __str__(self):
		return self.title

polls/models.py
from django.db import models
from django.utils import timezone
import datetime

class Poll(models.Model):
	question = models.CharField(max_length=200)
	pub_date = models.DateTimeField('date published')
	def was_published_recently(self):
		return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
	was_published_recently.admin_order_field = 'pub_date'
	was_published_recently.boolean = True
	was_published_recently.short_description = 'Published recently?'
	def __unicode__(self):  # Python 3: def __str__(self):
		return self.question

class Choice(models.Model):
    poll = models.ForeignKey(Poll)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __unicode__(self):  # Python 3: def __str__(self):
        return self.choice_text
# Create your models here.

blog/views.py
from django.shortcuts import get_object_or_404, render, render_to_response
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic
from blog.models import Post, TitledPost
from django.core.paginator import Paginator, EmptyPage

class IndexView(generic.ListView):
    template_name = 'blog/index.html'
    context_object_name = 'latest_post_list'

    def get_queryset(self):
        """Return the last five published polls."""
        return Post.objects.order_by('-pub_date')[:5]

def getRecentPosts(request, selected_page=1):
	# Get all blog posts
	posts = TitledPost.objects.all().order_by('-pub_date')

	# Sort posts into chronological order
	posts = Paginator(posts, 5)
	
	try:
		returned_page = posts.page(selected_page)
	except EmptyPage:
		returned_page = posts.page(posts.num_pages)

	# Display all the posts
	return render_to_response('titledposts.html', { 'posts':returned_page.object_list,'page':returned_page})
	
def getPost(request, postSlug):
    # Get specified post
    post = TitledPost.objects.filter(slug=postSlug)

    # Display specified post
    return render_to_response('posts.html', { 'posts':post})

polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic

from polls.models import Choice, Poll

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_poll_list'

    def get_queryset(self):
        """Return the last five published polls."""
        return Poll.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Poll
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Poll
    template_name = 'polls/results.html'

def vote(request, poll_id):
	p = get_object_or_404(Poll, pk=poll_id)
	try:
		selected_choice = p.choice_set.get(pk=request.POST['choice'])
	except (KeyError, Choice.DoesNotExist):
		# Redisplay the poll voting form.
		return render(request, 'polls/detail.html', {
			'poll': p,
			'error_message': "You didn't select a choice.",
			})
	else:
		selected_choice.votes += 1
		selected_choice.save()
		# Always return an HttpResponseRedirect after successfully dealing
		# with POST data. This prevents data from being posted twice if a
		# user hits the Back button.
		return HttpResponseRedirect(reverse('polls:results', args=(p.id,)))

blog/templates/blog/index.html
{% if latest_post_list %}
    <ul>
    {% for post in latest_post_list	 %}
        <li>{{post.text}}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No posts are available.</p>
{% endif %}

blog/templates/blog/posts.html
<html>
    <head>
        <title>My Django Blog</title>
    </head>
    <body>
        {% for post in posts %}
        <h1><a href="/blog/titledposts/{{ post.slug }}">{{ post.title }}</a></h1>
        <h3>{{ post.pub_date }}</h3>
        {{ post.text }}
        {% endfor %}
        <br />
    </body>
</html>

blog/templates/blog/titledposts.html
<html>
    <head>
        <title>My Django Blog</title>
    </head>
    <body>
        {% for post in posts %}
        <h1>{{ post.title }}</h1>
        <h3>{{ post.pub_date }}</h3>
        {{ post.text }}
        {% endfor %}
    </body>
	
	</br>
	</br>

    {% if page.has_previous %}
    <a href="/blog/titledposts/{{ page.previous_page_number }}/">Previous Page</a>
    {% endif %}
    {% if page.has_next %}
    <a href="/blog/titledposts/{{ page.next_page_number }}/">Next Page</a>
    {% endif %}
</html>

polls/templates/polls/detail.html
<h1>{{ poll.question }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' poll.id %}" method="post">
{% csrf_token %}
{% for choice in poll.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

polls/templates/polls/index.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

{% if latest_poll_list %}
    <ul>
    {% for poll in latest_poll_list %}
        <li><a href="{% url 'polls:detail' poll.id %}">{{poll.question}}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/polls/results.html
<h1>{{ poll.question }}</h1>

<ul>
{% for choice in poll.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' poll.id %}">Vote again?</a>